[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'yegappan/grep'

[[plugins]]
repo = 'vim-scripts/EnhCommentify.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'yuroyoro/vim-autoclose'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'vim-scripts/jQuery'

[[plugins]]
repo = 'tpope/vim-haml'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'ryoppy/vim-scp-upload'

[[plugins]]
repo = 'scrooloose/nerdtree'
